# Generated by Django 2.2.4 on 2019-09-02 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190902_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_category_id',
        ),
    ]
